@baseUrl = http://localhost:3002

### Get All Persons
GET {{baseUrl}}/api/persons

### Create Person
POST {{baseUrl}}/api/persons
Content-Type: application/json

{
  "name":"Ada Lovelac",
  "number": "3-44-5323523"
}

### Delete Person
DELETE {{baseUrl}}/api/persons/8891445346554555