@baseUrl = http://localhost:3002

### Get All Persons
GET {{baseUrl}}/api/persons

### Create Person
POST {{baseUrl}}/api/persons
Content-Type: application/json

{
  "name":"Anna",
  "number": "3-4-3523"
}

### Update Person
PUT {{baseUrl}}/api/persons/609a7e2f43dcf304455d0277
Content-Type: application/json

{
  "name":"Ann",
  "number": "3-4-323"
}

### Delete Person
DELETE {{baseUrl}}/api/persons/609

